# FROM fuzzers/go-fuzz:1.2.0
FROM golang:1.19 as builder

COPY . /aperture
WORKDIR /aperture/mayhem

RUN go install github.com/dvyukov/go-fuzz/go-fuzz@latest github.com/dvyukov/go-fuzz/go-fuzz-build@latest
RUN go get github.com/dvyukov/go-fuzz/go-fuzz-dep
RUN go get github.com/AdaLogics/go-fuzz-headers
RUN apt update && apt install -y clang


RUN go-fuzz-build -libfuzzer -o fuzzAperture.a && \
    clang -fsanitize=fuzzer fuzzAperture.a -o fuzzAperture.libfuzzer

FROM debian:bookworm-slim
COPY --from=builder /aperture/mayhem/fuzzAperture.libfuzzer /